const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY="planner-v7";
const OLD_KEY="planner-v6";
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2);
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const today=()=>iso(new Date());
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
let db=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(OLD_KEY)||"null")||{todos:[],tasks:[],subjects:[],habits:[],schedules:[]};
if(!db.todos)db.todos=[];if(!db.schedules)db.schedules=[];
let selectedDate=today(),calendarDate=new Date(),calendarView="month",taskFilter="next",habitDate=new Date();
let simpleConfig=null,clockMode="pomodoro",clockSeconds=1500,clockInitial=1500,clockInterval=null,pomo={focus:25,short:5,long:15};
let activeScheduleId=db.schedules[0]?.id||"";
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
function monday(d){const x=new Date(d);const n=(x.getDay()+6)%7;x.setDate(x.getDate()-n);x.setHours(12,0,0,0);return x}
function formatDate(v,o={weekday:"short",day:"numeric",month:"short"}){return new Intl.DateTimeFormat("ca-ES",o).format(new Date(v+"T12:00"))}
function endOfWeek(){const m=monday(new Date());const s=new Date(m);s.setDate(m.getDate()+6);return iso(s)}
function tomorrow(){const d=new Date();d.setDate(d.getDate()+1);return iso(d)}
function subjectName(id){return db.subjects.find(s=>s.id===id)?.name||""}
function taskTypeClass(type){return "type-"+String(type||"Altres").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g,"-")}
function renderAll(){renderHeader();renderTodos();renderTasks();renderCalendar();renderSubjects();renderHabits();renderTaskSubjects();renderClock();renderSchedules()}
function renderHeader(){$("#todayLabel").textContent=new Intl.DateTimeFormat("ca-ES",{weekday:"long",day:"numeric",month:"long"}).format(new Date())}
function renderTodos(){
 $("#todoList").innerHTML=db.todos.length?db.todos.map(t=>`<article class="todo-row"><button class="todo-check ${t.done?"done":""}" data-toggle-todo="${t.id}"></button><input class="todo-input" data-todo-input="${t.id}" value="${esc(t.text)}" aria-label="Editar element"><button class="text-btn" data-delete-todo="${t.id}">×</button></article>`).join(""):`<div class="empty">Escriu aquí coses ràpides que no necessiten data.</div>`;
}
function renderTasks(){
 let list=[...db.tasks];const m=iso(monday(new Date())),e=endOfWeek();
 if(taskFilter==="next")list=list.filter(t=>!t.done&&(t.date===today()||t.date===tomorrow()));
 if(taskFilter==="today")list=list.filter(t=>!t.done&&t.date===today());
 if(taskFilter==="tomorrow")list=list.filter(t=>!t.done&&t.date===tomorrow());
 if(taskFilter==="week")list=list.filter(t=>!t.done&&t.date>=m&&t.date<=e);
 if(taskFilter==="all")list=list.filter(t=>!t.done);
 if(taskFilter==="done")list=list.filter(t=>t.done);
 list.sort((a,b)=>a.date.localeCompare(b.date));
 $("#taskList").innerHTML=list.length?list.map(t=>`<article class="task"><button class="task-check ${t.done?"done":""}" data-toggle-task="${t.id}"></button><div class="task-main" data-edit-task="${t.id}"><strong>${esc(t.title)}</strong><div class="meta">${formatDate(t.date)}${t.subject?" · "+esc(subjectName(t.subject)):""}</div></div><span class="task-type ${taskTypeClass(t.type)}">${esc(t.type)}</span></article>`).join(""):`<div class="empty">No hi ha tasques en aquesta vista.</div>`;
}
function renderTaskSubjects(){$("#taskSubject").innerHTML='<option value="">Cap</option>'+db.subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("")}
function renderCalendar(){
 $$(".seg[data-calendar-view]").forEach(b=>b.classList.toggle("active",b.dataset.calendarView===calendarView));const c=$("#calendar");
 if(calendarView==="month"){
  $("#periodTitle").textContent=new Intl.DateTimeFormat("ca-ES",{month:"long",year:"numeric"}).format(calendarDate);const first=new Date(calendarDate.getFullYear(),calendarDate.getMonth(),1,12),start=monday(first);let html='<div class="weekdays">'+["Dl","Dt","Dc","Dj","Dv","Ds","Dg"].map(x=>`<div>${x}</div>`).join("")+'</div><div class="days">';
  for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const id=iso(d);html+=`<button class="day ${d.getMonth()!==calendarDate.getMonth()?"muted":""} ${id===today()?"today":""} ${id===selectedDate?"selected":""}" data-date="${id}">${d.getDate()}${db.tasks.some(t=>t.date===id&&!t.done)?'<i class="dot"></i>':""}</button>`}c.innerHTML=html+"</div>";
 }else if(calendarView==="week"){
  const m=monday(calendarDate),s=new Date(m);s.setDate(m.getDate()+6);$("#periodTitle").textContent=`${formatDate(iso(m))} – ${formatDate(iso(s))}`;
  c.innerHTML='<div class="week-cards">'+Array.from({length:7},(_,i)=>{const d=new Date(m);d.setDate(m.getDate()+i);const id=iso(d),items=db.tasks.filter(t=>t.date===id);return `<button class="week-card ${id===selectedDate?"selected":""} ${items.length?"":"empty"}" data-date="${id}"><strong>${new Intl.DateTimeFormat("ca-ES",{weekday:"short",day:"numeric"}).format(d)}</strong>${items.length?`<span>${items.length} ${items.length===1?"tasca":"tasques"}</span>`:""}</button>`}).join("")+"</div>";
 }else{
  const id=iso(calendarDate);$("#periodTitle").textContent=formatDate(id,{weekday:"long",day:"numeric",month:"long"});const ts=db.tasks.filter(t=>t.date===id);c.innerHTML=ts.length?ts.map(t=>`<article class="task" data-edit-task="${t.id}"><div class="task-main"><strong>${esc(t.title)}</strong><div class="meta">${esc(subjectName(t.subject)||"General")}</div></div><span class="task-type ${taskTypeClass(t.type)}">${esc(t.type)}</span></article>`).join(""):`<div class="empty">No hi ha res programat.</div>`;
 }
}
function openDay(id){selectedDate=id;calendarDate=new Date(id+"T12:00");$("#dayDialogDate").textContent=formatDate(id,{weekday:"long",day:"numeric",month:"long"});const items=db.tasks.filter(t=>t.date===id);$("#dayTaskList").innerHTML=items.length?items.map(t=>`<article class="task" data-edit-task="${t.id}"><button class="task-check ${t.done?"done":""}" data-toggle-task="${t.id}"></button><div class="task-main"><strong>${esc(t.title)}</strong><div class="meta">${esc(subjectName(t.subject)||"General")}</div></div><span class="task-type ${taskTypeClass(t.type)}">${esc(t.type)}</span></article>`).join(""):`<div class="empty">Aquest dia encara no té tasques.</div>`;$("#dayDialog").showModal()}
function renderSubjects(){$("#subjectsList").innerHTML=db.subjects.length?db.subjects.map(s=>{const tasks=db.tasks.filter(t=>t.subject===s.id).sort((a,b)=>a.date.localeCompare(b.date));return `<article class="subject-block"><div class="subject-head"><h3>${esc(s.name)}</h3><button class="text-btn" data-delete-subject="${s.id}">Eliminar</button></div>${tasks.length?tasks.map(t=>`<div class="subject-task" data-edit-task="${t.id}"><strong>${esc(t.title)}</strong><div class="meta">${formatDate(t.date)} · ${t.done?"Completada":"Pendent"}</div></div>`).join(""):'<div class="empty">Sense tasques.</div>'}</article>`}).join(""):'<div class="empty">Crea assignatures per ordenar les tasques.</div>'}
function renderHabits(){const y=habitDate.getFullYear(),m=habitDate.getMonth(),daysIn=new Date(y,m+1,0).getDate(),firstDay=(new Date(y,m,1).getDay()+6)%7;$("#habitMonthTitle").textContent=new Intl.DateTimeFormat("ca-ES",{month:"long",year:"numeric"}).format(habitDate);$("#habitsList").innerHTML=db.habits.length?db.habits.map(h=>{let cells="";for(let i=0;i<firstDay;i++)cells+='<span class="habit-day blank"></span>';for(let d=1;d<=daysIn;d++){const id=iso(new Date(y,m,d));cells+=`<button class="habit-day ${(h.days||{})[id]?"on":""}" data-habit="${h.id}" data-habit-date="${id}">${d}</button>`}return `<article class="habit-card"><div class="habit-head"><h3>${esc(h.name)}</h3><button class="text-btn" data-delete-habit="${h.id}">Eliminar</button></div><div class="weekdays">${["Dl","Dt","Dc","Dj","Dv","Ds","Dg"].map(x=>`<div>${x}</div>`).join("")}</div><div class="habit-month">${cells}</div></article>`}).join(""):'<div class="empty">Encara no has creat cap hàbit.</div>'}
function renderClock(){$$(".seg[data-clock-mode]").forEach(b=>b.classList.toggle("active",b.dataset.clockMode===clockMode));if(clockMode==="clock"){$("#clockDisplay").textContent=new Intl.DateTimeFormat("ca-ES",{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date());$("#clockControls").innerHTML=`<div class="meta">${new Intl.DateTimeFormat("ca-ES",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date())}</div>`;return}const m=Math.floor(clockSeconds/60),s=clockSeconds%60;$("#clockDisplay").textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;if(clockMode==="pomodoro"){$("#clockControls").innerHTML=`<div class="clock-settings"><label>Focus<input id="pFocus" type="number" value="${pomo.focus}" min="1"></label><label>Descans<input id="pShort" type="number" value="${pomo.short}" min="1"></label><label>Descans llarg<input id="pLong" type="number" value="${pomo.long}" min="1"></label></div><div class="clock-controls"><button class="dark compact" id="clockStart">${clockInterval?"Pausar":"Començar"}</button><button class="soft compact" id="clockReset">Reiniciar</button></div>`}else{$("#clockControls").innerHTML=`<div class="clock-settings"><label>Minuts<input id="timerMinutes" type="number" value="${Math.floor(clockInitial/60)}" min="0"></label></div><div class="clock-controls"><button class="dark compact" id="clockStart">${clockInterval?"Pausar":"Començar"}</button><button class="soft compact" id="clockReset">Reiniciar</button></div>`}$("#clockStart")?.addEventListener("click",toggleClock);$("#clockReset")?.addEventListener("click",resetClock);$("#pFocus")?.addEventListener("change",e=>{pomo.focus=Number(e.target.value);clockInitial=pomo.focus*60;clockSeconds=clockInitial;renderClock()});$("#pShort")?.addEventListener("change",e=>pomo.short=Number(e.target.value));$("#pLong")?.addEventListener("change",e=>pomo.long=Number(e.target.value));$("#timerMinutes")?.addEventListener("change",e=>{clockInitial=Number(e.target.value)*60;clockSeconds=clockInitial;renderClock()})}
function toggleClock(){if(clockInterval){clearInterval(clockInterval);clockInterval=null;renderClock();return}clockInterval=setInterval(()=>{clockSeconds--;if(clockSeconds<=0){clearInterval(clockInterval);clockInterval=null;alert("Temps completat");clockSeconds=clockInitial}renderClock()},1000);renderClock()}
function resetClock(){clearInterval(clockInterval);clockInterval=null;clockSeconds=clockInitial;renderClock()}
function renderSchedules(){if(!db.schedules.length){db.schedules.push({id:uid(),name:"Horari principal",mode:"manual",items:[],photo:""});activeScheduleId=db.schedules[0].id;localStorage.setItem(KEY,JSON.stringify(db))}if(!db.schedules.some(s=>s.id===activeScheduleId))activeScheduleId=db.schedules[0].id;$("#scheduleSelector").innerHTML=db.schedules.map(s=>`<option value="${s.id}" ${s.id===activeScheduleId?"selected":""}>${esc(s.name)}</option>`).join("");const s=db.schedules.find(x=>x.id===activeScheduleId);if(s.mode==="photo"){$("#scheduleContent").innerHTML=`<div class="schedule-shell"><label class="photo-upload"><input id="schedulePhotoInput" type="file" accept="image/*"><span>${s.photo?"Canviar fotografia":"Seleccionar fotografia"}</span></label>${s.photo?`<img class="schedule-photo" src="${s.photo}" alt="${esc(s.name)}">`:""}<button class="text-btn" data-delete-schedule-profile="${s.id}">Eliminar horari</button></div>`;$("#schedulePhotoInput").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{s.photo=r.result;save()};r.readAsDataURL(f)}}else{const days=["Dilluns","Dimarts","Dimecres","Dijous","Divendres"];$("#scheduleContent").innerHTML=`<div class="section-head"><h3>${esc(s.name)}</h3><button class="dark compact" id="addScheduleItem">Afegir</button></div><div class="schedule-week">${days.map((day,i)=>{const items=(s.items||[]).filter(x=>Number(x.day)===i).sort((a,b)=>a.start.localeCompare(b.start));return `<div class="schedule-col"><h3>${day}</h3>${items.length?items.map(x=>`<article class="schedule-item"><button class="schedule-delete" data-delete-schedule-item="${x.id}">×</button><span class="schedule-time">${esc(x.start)}–${esc(x.end)}</span><strong>${esc(x.name)}</strong><div class="meta">${esc(x.place||"")}</div></article>`).join(""):'<div class="meta">Sense classes</div>'}</div>`}).join("")}</div><button class="text-btn" data-delete-schedule-profile="${s.id}">Eliminar horari</button>`;$("#addScheduleItem").onclick=()=>openSimple("Afegir classe",[{name:"name",label:"Assignatura o activitat",required:true},{name:"day",label:"Dia (0 dilluns – 4 divendres)",type:"number",value:"0",required:true},{name:"start",label:"Hora inici",type:"time",required:true},{name:"end",label:"Hora final",type:"time",required:true},{name:"place",label:"Aula o lloc"}],v=>{s.items=s.items||[];s.items.push({id:uid(),...v});save()})}}
function openTask(t=null,date=selectedDate){$("#taskDialogTitle").textContent=t?"Editar tasca":"Nova tasca";$("#taskId").value=t?.id||"";$("#taskTitle").value=t?.title||"";$("#taskDate").value=t?.date||date;$("#taskSubject").value=t?.subject||"";$("#taskType").value=t?.type||"AC";$("#taskComments").value=t?.comments||"";$("#deleteTaskBtn").classList.toggle("hidden",!t);$("#taskDialog").showModal()}
function openSimple(title,fields,onSave){simpleConfig={fields,onSave};$("#simpleTitle").textContent=title;$("#simpleFields").innerHTML=fields.map(f=>`<label>${f.label}<input id="sf-${f.name}" type="${f.type||"text"}" value="${esc(f.value||"")}" ${f.required?"required":""}></label>`).join("");$("#simpleDialog").showModal()}
function showScreen(id){$$(".screen").forEach(s=>s.classList.toggle("active",s.id===id));$$(".nav-item").forEach(n=>n.classList.toggle("active",n.dataset.screen===id));$("#menuSheet").classList.remove("open");window.scrollTo({top:0,behavior:"smooth"})}

document.addEventListener("change",e=>{const todo=e.target.closest("[data-todo-input]");if(todo){const t=db.todos.find(x=>x.id===todo.dataset.todoInput);const value=todo.value.trim();if(value){t.text=value;save()}else todo.value=t.text}});
document.addEventListener("input",e=>{const ti=e.target.closest("[data-todo-input]");if(ti){const t=db.todos.find(x=>x.id===ti.dataset.todoInput);if(t){t.text=ti.value;localStorage.setItem(KEY,JSON.stringify(db))}}});
document.addEventListener("change",e=>{const ti=e.target.closest("[data-todo-input]");if(ti){const t=db.todos.find(x=>x.id===ti.dataset.todoInput);if(t){t.text=ti.value.trim()||"Nova tasca";save()}}});
document.addEventListener("keydown",e=>{const ti=e.target.closest("[data-todo-input]");if(ti&&e.key==="Enter"){e.preventDefault();ti.blur()}});
document.addEventListener("click",e=>{const screen=e.target.closest("[data-screen]");if(screen){showScreen(screen.dataset.screen);return}const date=e.target.closest("[data-date]");if(date){openDay(date.dataset.date);return}const toggle=e.target.closest("[data-toggle-task]");if(toggle){const t=db.tasks.find(x=>x.id===toggle.dataset.toggleTask);t.done=!t.done;save();if($("#dayDialog").open)openDay(selectedDate);return}const edit=e.target.closest("[data-edit-task]");if(edit){openTask(db.tasks.find(x=>x.id===edit.dataset.editTask));return}const tt=e.target.closest("[data-toggle-todo]");if(tt){const t=db.todos.find(x=>x.id===tt.dataset.toggleTodo);t.done=!t.done;save();return}if(e.target.dataset.deleteTodo){db.todos=db.todos.filter(x=>x.id!==e.target.dataset.deleteTodo);save()}const habit=e.target.closest("[data-habit]");if(habit){const h=db.habits.find(x=>x.id===habit.dataset.habit);h.days=h.days||{};h.days[habit.dataset.habitDate]=!h.days[habit.dataset.habitDate];save();return}if(e.target.dataset.deleteHabit){db.habits=db.habits.filter(x=>x.id!==e.target.dataset.deleteHabit);save()}if(e.target.dataset.deleteSubject){db.tasks.forEach(t=>{if(t.subject===e.target.dataset.deleteSubject)t.subject=""});db.subjects=db.subjects.filter(x=>x.id!==e.target.dataset.deleteSubject);save()}if(e.target.dataset.deleteScheduleItem){const s=db.schedules.find(x=>x.id===activeScheduleId);s.items=s.items.filter(x=>x.id!==e.target.dataset.deleteScheduleItem);save()}if(e.target.dataset.deleteScheduleProfile){if(db.schedules.length===1)return alert("Has de conservar almenys un horari.");db.schedules=db.schedules.filter(x=>x.id!==e.target.dataset.deleteScheduleProfile);activeScheduleId=db.schedules[0].id;save()}const close=e.target.closest("[data-close-dialog]");if(close)$("#"+close.dataset.closeDialog).close()});
$("#addTodo").onclick=()=>{db.todos.push({id:uid(),text:"Nova tasca ràpida",done:false});save();setTimeout(()=>{const inputs=$$("[data-todo-input]");inputs.at(-1)?.select()},30)};
$("#createTaskForDay").onclick=()=>{$("#dayDialog").close();openTask(null,selectedDate)};
$("#calendarAddTask").onclick=()=>openTask(null,selectedDate);
$("#menuBtn").onclick=()=>$("#menuSheet").classList.add("open");$("#closeMenu").onclick=()=>$("#menuSheet").classList.remove("open");
$$("[data-task-filter]").forEach(b=>b.onclick=()=>{taskFilter=b.dataset.taskFilter;$$("[data-task-filter]").forEach(x=>x.classList.toggle("active",x===b));renderTasks()});
$$("[data-calendar-view]").forEach(b=>b.onclick=()=>{calendarView=b.dataset.calendarView;renderCalendar()});
$("#prevPeriod").onclick=()=>{calendarView==="month"?calendarDate.setMonth(calendarDate.getMonth()-1):calendarView==="week"?calendarDate.setDate(calendarDate.getDate()-7):calendarDate.setDate(calendarDate.getDate()-1);renderCalendar()};
$("#nextPeriod").onclick=()=>{calendarView==="month"?calendarDate.setMonth(calendarDate.getMonth()+1):calendarView==="week"?calendarDate.setDate(calendarDate.getDate()+7):calendarDate.setDate(calendarDate.getDate()+1);renderCalendar()};
$("#taskForm").onsubmit=e=>{e.preventDefault();const id=$("#taskId").value,obj={id:id||uid(),title:$("#taskTitle").value.trim(),date:$("#taskDate").value,subject:$("#taskSubject").value,type:$("#taskType").value,comments:$("#taskComments").value,done:false};if(id){const old=db.tasks.find(x=>x.id===id);obj.done=old.done;db.tasks=db.tasks.map(x=>x.id===id?obj:x)}else db.tasks.push(obj);save();$("#taskDialog").close()};
$("#deleteTaskBtn").onclick=()=>{db.tasks=db.tasks.filter(x=>x.id!==$("#taskId").value);save();$("#taskDialog").close()};
$("#addSubjectBtn").onclick=()=>openSimple("Nova assignatura",[{name:"name",label:"Nom",required:true}],v=>{db.subjects.push({id:uid(),name:v.name});save()});
$("#addHabitBtn").onclick=()=>openSimple("Nou hàbit",[{name:"name",label:"Nom",required:true}],v=>{db.habits.push({id:uid(),name:v.name,days:{}});save()});
$("#habitPrev").onclick=()=>{habitDate.setMonth(habitDate.getMonth()-1);renderHabits()};$("#habitNext").onclick=()=>{habitDate.setMonth(habitDate.getMonth()+1);renderHabits()};$("#habitToday").onclick=()=>{habitDate=new Date();renderHabits()};
$("#simpleForm").onsubmit=e=>{e.preventDefault();const v={};simpleConfig.fields.forEach(f=>v[f.name]=$("#sf-"+f.name).value);simpleConfig.onSave(v);$("#simpleDialog").close()};
$$("[data-clock-mode]").forEach(b=>b.onclick=()=>{clearInterval(clockInterval);clockInterval=null;clockMode=b.dataset.clockMode;if(clockMode==="pomodoro"){clockInitial=pomo.focus*60;clockSeconds=clockInitial}else if(clockMode==="timer"){clockInitial=10*60;clockSeconds=clockInitial}renderClock()});
$("#fullscreenBtn").onclick=()=>$("#clockPanel").classList.add("fullscreen");$("#minimizeClock").onclick=()=>$("#clockPanel").classList.remove("fullscreen");
$("#newScheduleBtn").onclick=()=>$("#scheduleDialog").showModal();$("#scheduleForm").onsubmit=e=>{e.preventDefault();const s={id:uid(),name:$("#scheduleName").value.trim(),mode:$("#scheduleMode").value,items:[],photo:""};db.schedules.push(s);activeScheduleId=s.id;save();$("#scheduleDialog").close();e.target.reset()};$("#scheduleSelector").onchange=e=>{activeScheduleId=e.target.value;renderSchedules()};
setInterval(()=>{if(clockMode==="clock")renderClock()},1000);if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"));renderAll();
